### ISSUE TITLE
Not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by wxguy** [dmo60/CoverflowAltTab#112]
It is not working on latest Ubuntu 19.04. Installed the extension from extensions.gnome site.

**Comment by PJSingh5000** [comment]
Not working in Ubuntu 9.10 with Gnome 3.34.1. The cover-flow animation is not there, although pressing Alt-Tab does activate the next window.

**Comment by PJSingh5000** [comment]
I see these two errors while trying to use Alt-Tab...

(By the way, I have this extension installed in `usr/share/gnome-shell/extensions` and the `CoverflowAltTab@palatis.blogspot.com` directory is owned by root).

```
gnome-shell

JS ERROR: TypeError: texture.get_size is not a function
_createPreviews@/usr/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:75:39
show@/usr/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js:111:9
```

```
xdg-desktop-por

Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed
```

**Comment by p91paul** [comment]
Hi, I have yet to find time to upload this to e.g.o., but you can uninstall your current version and install manually from here on github, instructions are provided on the homepage.

@PJSingh5000 given the location of your installation you probably installed an unofficial package from a third party; I just created v1.8 tag here on github, you can direct the maintainers of your package to build a new version.

**Comment by wxguy** [comment]
I can confirm that installing extension from github repo works fine on ubuntu 19.10. You may want to keep an entry regarding this in the readme file so that it benefits others as well.

**Comment by PJSingh5000** [comment]
@p91paul, I usually download my extensions from extensions.gnome.org, and I just copy them to /usr/share/gnome-shell/extensions so they are available globally for all users.

From your perspective, is extensions.gnome.org considered a third party? If so, I will be sure to get this extension from here, in the future.

I can see that v1.8 from github is working for @wxguy. I'll try it in a few minutes.

**Comment by p91paul** [comment]
ok if you are getting from ego disregard my comment.

**Comment by PJSingh5000** [comment]
Just tried it from Github... Works smoothly! Thanks. :)

**Comment by p91paul** [comment]
I uploaded to extensions.gnome.org, now we are waiting for reviewers to release it! Thanks for your help!

**Comment by PJSingh5000** [comment]
Good news! Please update us once they approve it, and I will test.

Thanks, again... We all really appreciate your hard work!
