### ISSUE TITLE
Some javascript problems on gnome-shell 3.34

### ISSUE THREAD

**Issue by terencode** [dmo60/CoverflowAltTab#108]
The following always shows: 
```
Usage of object.actor is deprecated for Panel
                                                  get@resource:///org/gnome/shell/ui/environment.js:240:29
                                                  show/<@/usr/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:120:17
                                                  show@/usr/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:118:9
sept. 24 11:20:29 terence-arch gnome-shell[1609]: Usage of object.actor is deprecated for Panel
```

The following is when DashToDock is installed but only with coverflow alt-tab enabled as well:
```
Usage of object.actor is deprecated for DashToDock_MyDash
                                                  get@resource:///org/gnome/shell/ui/environment.js:240:29
                                                  _onDestroy/<@/usr/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:514:25
                                                  _onDestroy@/usr/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:509:13
                                                  destroy@/usr/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:567:9
                                                  _keyPressEvent@/usr/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:305:17
```

And finally these are spammed and seem  to trigger after cycling between the windows:
```
Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on ClutterClone
```

**Comment by alex4401** [comment]
Surprisingly, I can't seem to be able to reproduce the .actor deprecation notices, but I'm getting lots of out of range values while switching - was this a case before?

```
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "-44,316982" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "-41,643566" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "4294967280" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "-33,516903" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "-31,494999" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "4294967286" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "-21,574982" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "-20,273476" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "4294967291" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
wrz 25 21:18:04 alexpc gnome-shell[1099]: value "-10,306070" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
```

Back to the topic though, could you please check whether a5941bd on my [g3.34-actor-deprecation](https://github.com/alex4401/CoverflowAltTab/tree/g3.34-actor-deprecation) branch silences the deprecation notices?

**Comment by alex4401** [comment]
Possibly useful:
```
wrz 25 21:55:19 alexpc gnome-shell[9421]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutt>
wrz 25 21:55:19 alexpc gnome-shell[9421]: The offending signal was destroy on ClutterClone 0x5580b125f520.
wrz 25 21:55:19 alexpc gnome-shell[9421]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutt>
wrz 25 21:55:19 alexpc gnome-shell[9421]: The offending signal was destroy on ClutterClone 0x5580b125f1c0.
wrz 25 21:55:19 alexpc gnome-shell[9421]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutt>
wrz 25 21:55:19 alexpc gnome-shell[9421]: The offending signal was destroy on ClutterClone 0x5580b125eb00.
wrz 25 21:55:19 alexpc gnome-shell[9421]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutt>
wrz 25 21:55:19 alexpc gnome-shell[9421]: The offending signal was destroy on ClutterClone 0x5580b125ee60.
wrz 25 21:55:19 alexpc gnome-shell[9421]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutt>
wrz 25 21:55:19 alexpc gnome-shell[9421]: The offending signal was destroy on StLabel 0x5580b13ec470.
wrz 25 21:55:19 alexpc gnome-shell[9421]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutt>
wrz 25 21:55:19 alexpc gnome-shell[9421]: The offending signal was destroy on StBin 0x5580b0112880.
```
The signals are always `destroy` but they happen on StBin, StLabel and ClutterClones.

**Comment by terencode** [comment]
>Surprisingly, I seem to be unable to reproduce the .actor deprecation notices, but I'm getting lots of out of range values while switching - was this a case before?

Yes even before 3.34 from what I remember.

>could you please check whether a5941bd on my g3.34-actor-deprecation branch silences the deprecation notices?

It does but it produces/didn't fix those: 
```
JS WARNING: [/home/terence/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/timelineSwitcher.js 114]: reference to undefined property "_previews"
sept. 25 21:59:34 terence-arch gnome-shell[1609]: JS ERROR: TypeError: this._previews is undefined
                                                  _updatePreviews@/home/terence/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/timelineSwitcher.js:114:1
                                                  _previewNext@/home/terence/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/timelineSwitcher.js:104:9
                                                  _next@/home/terence/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:178:13
                                                  _keyPressEvent@/home/terence/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:322:21
```

**Comment by alex4401** [comment]
Interesting. I don't have these on my local machine with a5941bd. After a brief look through the timeline switcher's code, I noticed _previews is created only in _createPreviews and the call that causes the warning for you is in _updatePreviews. I'll add a null check on a separate branch.

**Comment by terencode** [comment]
Do I apply 07ad39f  on top of  a5941bd ?

**Comment by terencode** [comment]
With both applied I get this: 
```
JS WARNING: [/home/terence/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js 472]: reference to undefined property "_initialDelayTimeoutId"
```

and the usual `The offending signal was destroy on ...`

**Comment by alex4401** [comment]
Try 4743f89 and see if it silences the offending signal messages - possible there are some side-effects though.

Missing `_initialDelayTimeoutId` is a bit worrying - it seems to further confirm my theory that the switcher gets destroyed before it's even fully created.

**Comment by terencode** [comment]
With `4743f89`, it's like the extension is disabled (the old alt-tab shows up) and no errors/warnings shown in the logs. 
(good night)

**Comment by alex4401** [comment]
What are your settings? Maybe that'll help me to reproduce that as it's working fine on my machine.

Also, are any errors reported (for this extension) in the extensions tab of the looking glass (`Alt`+`F2` and type in `lg`)?

**Comment by terencode** [comment]
If I open the settings while the extension is enabled and switch between timeline and coverflow this happens: 
```
Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
sept. 26 13:48:00 terence-arch gnome-shell-ext[1842030]: The offending signal was destroy on Gjs_ExtensionRow 0x55f10276a500.
```

In addition to that what I described early is when I restart the shell with the extension enabled. 
If I disable and enable it back, it will work again.

**Comment by alex4401** [comment]
I hope someone else is able to find a solution then, as I currently have no ideas how to solve GC spam.

**Comment by lverissimo** [comment]
stoped working for me too on gnome 3.34

**Comment by alex4401** [comment]
@lverissimo Huh, that's new considering it actually stopped working for you. Could you post your GNOME Shell's log?

**Comment by henrik-wittenberg** [comment]
Does not work on manjaro with gnome version 3.34.1

**Comment by alex4401** [comment]
@henrik-wittenberg Could you post the journal for GNOME Shell?

**Comment by TimTomTwo** [comment]
@henrik-wittenberg 
Hi,
I've got the same problem on Manjaro for a couple of days/weeks now. Alt-Tab seems to be working fine, but the the animation is not visible. Here is some snippet of my journalctl output:

`Okt 20 18:01:57 my-linux gnome-shell[1734]: JS ERROR: TypeError: texture.get_size is not a function
                                            _createPreviews@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:75:39
                                            show@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js:111:9
Okt 20 18:01:58 my-linux gnome-shell[1734]: Source ID 8984 was not found when attempting to remove it
Okt 20 18:01:58 my-linux gnome-shell[1734]: JS ERROR: TypeError: texture.get_size is not a function
                                            _createPreviews@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:75:39
                                            show@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js:111:9
Okt 20 18:01:59 my-linux gnome-shell[1734]: Source ID 9037 was not found when attempting to remove it
Okt 20 18:04:30 my-linux gnome-shell[1734]: JS ERROR: TypeError: texture.get_size is not a function
                                            _createPreviews@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:75:39
                                            show@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js:111:9
Okt 20 18:04:30 my-linux gnome-shell[1734]: Source ID 10095 was not found when attempting to remove it
Okt 20 18:04:32 my-linux gnome-shell[1734]: JS ERROR: TypeError: texture.get_size is not a function
                                            _createPreviews@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:75:39
                                            show@/home/ttimar/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js:111:9`

hope this helps

**Comment by alex4401** [comment]
@TimTomTwo Thank you for the journal! It looks like you're using a version that hasn't been fixed yet. Try using the code at master branch.

@p91paul Did the patch hit the GNOME extension repository?

**Comment by TimTomTwo** [comment]
@alex4401 
Yeah, I installed it with extensions.gnome.org.
Works now again with the current master code.
Thx!

**Comment by henrik-wittenberg** [comment]
Cloning the master branch code worked for me, too. :-)

**Comment by p91paul** [comment]
sorry guys, I haven't got a minute in the last few weeks. The main bug here is still #95 unfortunately.

**Comment by p91paul** [comment]
I uploaded the extension to extensions.gnome.org, now it is pending review.

**Comment by p91paul** [comment]
v40 is available on extensions.gnome.org!

**Comment by alex4401** [comment]
@p91paul There's still an issue left that isn't solved yet (GC cries of horror) and that's what the issue was about before #106 started leaking into it.

**Comment by p91paul** [comment]
no, I didn't realize this thread was hijacked and started to think it was about 3.34 compatibility only.

**Comment by machitgarha** [comment]
Hi. Aren't there any fixes for this bug yet? I'm still getting "Attempting to call back into JSAPI during the sweeping phase of GC." warnings.

Nonetheless, I tried to reproduce the same warning. Here are the results:

## Steps to Reproduce

0. Install the extension.
1. Enable the extension.
2. Press Alt + Tab to switch windows.
3. Bunch of warnings (or the like) should be logged into `journalctl`, like this:

```
Aug 09 13:16:01 username gnome-shell[33333]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Aug 09 13:16:01 machitgarha gnome-shell[33333]: The offending signal was destroy on ClutterClone 0x5559499d7490.
```

### Notes

- It's always reproducable when you switch between windows.
- Changing extension settings does not prevent the warnings from being happened.
- It seems the warning happens exactly when you enter the coverflow state, and does not happen when you press Tab (or Shift + Tab) to switch windows. Plus, as it seems, exiting coverflow state does not lead to warnings.
- The count of warnings corresponds to the count of rendered windows, plus two. Those two happens every time you enter coverflow state, and are related to `StBin` and `StLabel`, and the others are `ClutterClone`. By rendered windows, I mean, if you set to show you all windows in the current workspace, only those windows; but if you set to show you all windows across all workspaces, all windows in all workspaces.

## System Information

- OS: Fedora 32 (Workstation Edittion)
- Kernel: Linux 5.7.11(-200.fc32.x86_64)
- Gnome Shell 3.36.4 (Mutter 3.36.4)

Hope it helps.

**Comment by machitgarha** [comment]
For the sake of knowledge, the error happens [here](https://github.com/mtwebster/gjs/blob/1512096fe02661aeb7ceee2cbde5a47d80ca1ec0/gi/value.cpp#L144), in GJS library itself.

**Comment by machitgarha** [comment]
@alex4401 Yes, I know. However, I try to find what exactly is happening in the underlying layer in GJS, and then, understand where is the problem in the extension itself. Maybe there are better solutions for this, but, I prefer to do so. And if you have another solution (perhaps being easier), we all can benefit from you.

**Comment by alex4401** [comment]
Sorry if this sounded hostile. The error is probably caused by a stray actor that gets collected by GC. Actor has surely a destroy signal connected, which can't be invoked because Gjs is locked for the duration of garbage collection.

The extension needs to be scanned for such actors and they have to be disposed of manually if the destroy signals are needed.

**Comment by machitgarha** [comment]
@alex4401 Good. Because of the place of the error, I thought the GC would mean GClojure, not Garbage Collection. I'll look further into it. Thanks for your comment (it was not really hostile).

**Comment by machitgarha** [comment]
The problems mainly happen [here](https://github.com/dmo60/CoverflowAltTab/blob/master/CoverflowAltTab%40dmo60.de/switcher.js#L576). We are not destroying previews, window title and icon at the end, just before setting them to null. This patch removes the whole errors:

```
        ...
        this._windowManager.disconnect(this._mcid);

        # The patch: Destroy things before setting them to null
        this._windowTitle.destroy();
        this._icon.destroy();
        for (let i of this._previews) {
            i.destroy();
        }

        this._windows = null;
        this._windowTitle = null;
        ...
```

This also breaks the extension at destroying time. The reason is, the Tweener does not wait and returns, and thus, destroying happens just before the Tweener makes its job done. Applying this patch, and adding a wait lock for the Tweener fixes the current issue.

**Comment by alex4401** [comment]
You could try adding a Tweener.removeTweens call for all of the destroyed actors which get tweened before.

**Comment by machitgarha** [comment]
@alex4401 Does `Tweener.removeTweens()` wait for the tweens to end? Doesn't it just remove them?

**Comment by machitgarha** [comment]
@alex4401 Maybe we should use `onComplete` inside `Tweener.addTweens()` instead?

**Comment by alex4401** [comment]
That should work as well I guess, without interrupting the animation if the switcher isn't hidden by this point, but I haven't used the extension for few months now and I'm probably wrong on this one.

**Comment by p91paul** [comment]
I cannot reproduce this on Gnome 40.
I don't know if it was solved by code improvements in the various pull requests or by Gnome new versions, but I'm going to close this.
If anyone reproduces on Gnome 40, please let me know and I will reopen.

**Comment by machitgarha** [comment]
@p91paul Reproducable for me on Gnome 40. Please re-open it. Thanks. :)

**Comment by p91paul** [comment]
@machitgarha @dsheeler can you confirm #158 fixed this as well?

**Comment by machitgarha** [comment]
@p91paul I think so. The diff of the PR seems to fix this (adding `onComplete` event handler). Plus, I'm not able to reproduce it on my Fedora 35 box.

So, thanks @dsheeler for fixing this as well!
