### PR TITLE
Make compatible with GNOME 3.36

### LINKED ISSUE #117: coverflow not compatible with gnome-shell 3.36
In gnome-shell 3.35.91-1ubuntu2, pressing alt-tab with coverflow enabled does nothing.

gnome-tweaks doesn't show any error for coverflow, but this error appears in the journal:

```
Mar 03 05:37:12 xps15 gnome-shell[2053]: JS ERROR: TypeError: 

this._backgroundGroup.lower_bottom is not a function

                                         initBackground@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/platform.js:514:9

                                         _init@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js:65:7

                                         _init@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:53:9

                                         Switcher@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:46:5

                                         _startWindowSwitcher@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/manager.js:142:28

```

### PR DESCRIPTION
**Pull request by alex4401**
Works for me on Arch Linux with the Timeline switcher.

Coverflow switcher and different settings need some extra testing.

Fixes #117, I believe.

### CODE REVIEW

**Comment by frol** [comment]
I confirm that the patch works on Arch Linux with Gnome Shell 3.36.

@alex4401 Thank you for your patch!
